#!/bin/bash
#
# rpmbuild: wrap rpmbuild to build in isolated dir, such as unrpm creates
#

main() {
    declare x topdir
    for x; do
        x=$(readlink -f "$x" 2>/dev/null)
        if [[ $x == */SPECS/*.spec ]]; then
            topdir=$(dirname "$(dirname "$x")")
            break
        elif [[ $1 == -t* ]]; then
            case $x in
                *.tar.gz|*.tar.bz2) topdir=${x%.*.*}; break ;;
                *.tgz|*.tbz2)       topdir=${x%.*};   break ;;
            esac
        fi
    done

    set -e

    declare cmd status=0

    # it sucks when rpmbuild bombs because of missing dirs
    [[ -z $topdir ]] || topdir=$(readlink -f $topdir)
    [[ -z $topdir ]] || mkdir -p "$topdir/"{SPECS,SOURCES,BUILD,RPMS,SRPMS}

    cmd=( 
        /usr/bin/rpmbuild
        ${topdir:+--define="_topdir $topdir"}
        "$@"
    )
    printf "%q " "${cmd[@]}"; echo

    # log rpmbuild output
    [[ -z $topdir ]] || exec 3>&1 4>&2 1> >(tee $topdir/rpmbuild-$$.out) 2>&1
    "${cmd[@]}" || status=$?
    [[ -z $topdir ]] || exec 1>&3- 2>&4-

    exit $status
}

echo() {
    printf '%s\n' "$*"
}

die() {
    declare status=1
    if [[ $1 == ?* && $1 != *[!0-9]* ]]; then
        status=$1
        shift
    fi
    echo "$cmd: ${*:-error}" >&2
    exit $status
}

main "$@"
